package edu.eci.cosw.jpa.sample.model;
// Generated Mar 9, 2016 7:01:57 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Consultas generated by hbm2java
 */
@Entity
@Table(name = "CONSULTAS")
public class Consulta  implements java.io.Serializable {


     private Integer idConsultas;     
     private Date fechaYHora;
     private String resumen;

    public Consulta() {
    }

    public Consulta(Date fechaYHora, String resumen) {       
       this.fechaYHora = fechaYHora;
       this.resumen = resumen;
    }
   
    @Id
    @GeneratedValue
    public Integer getIdConsultas() {
        return this.idConsultas;
    }
    
    public void setIdConsultas(Integer idConsultas) {
        this.idConsultas = idConsultas;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_y_hora")
    public Date getFechaYHora() {
        return this.fechaYHora;
    }
    
    public void setFechaYHora(Date fechaYHora) {
        this.fechaYHora = fechaYHora;
    }
    
    @Column(name="resumen")
    public String getResumen() {
        return this.resumen;
    }
    
    public void setResumen(String resumen) {
        this.resumen = resumen;
    }

    @Override
    public String toString() {
        return "Consulta{" + "idConsultas=" + idConsultas + ", fechaYHora=" + fechaYHora + ", resumen=" + resumen + '}';
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 67 * hash + Objects.hashCode(this.idConsultas);
        hash = 67 * hash + Objects.hashCode(this.fechaYHora);
        hash = 67 * hash + Objects.hashCode(this.resumen);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Consulta other = (Consulta) obj;
        if (!Objects.equals(this.resumen, other.resumen)) {
            return false;
        }
        if (!Objects.equals(this.idConsultas, other.idConsultas)) {
            return false;
        }
        if (!Objects.equals(this.fechaYHora, other.fechaYHora)) {
            return false;
        }
        return true;
    }




}


