package edu.eci.cosw.jpa.sample.model;
// Generated Mar 9, 2016 7:01:57 AM by Hibernate Tools 4.3.1

import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Embeddable;



/**
 * PacientesId generated by hbm2java
 */
@Embeddable
public class PacienteId  implements java.io.Serializable {


     private int id;
     private String tipoId;

    public PacienteId() {
    }

    public PacienteId(int id, String tipoId) {
       this.id = id;
       this.tipoId = tipoId;
    }
   
    @Column(name = "id")
    public int getId() {
        return this.id;
    }
        
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name = "tipo_id")
    public String getTipoId() {
        return this.tipoId;
    }
    
    public void setTipoId(String tipoId) {
        this.tipoId = tipoId;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 37 * hash + this.id;
        hash = 37 * hash + Objects.hashCode(this.tipoId);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final PacienteId other = (PacienteId) obj;
        if (this.id != other.id) {
            return false;
        }
        if (!Objects.equals(this.tipoId, other.tipoId)) {
            return false;
        }
        return true;
    }

 

    @Override
    public String toString() {
        return "PacienteId{" + "id=" + id + ", tipoId=" + tipoId + '}';
    }


}


